//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneFit
{
    public partial class CustomerActivity
    {
        protected global::System.Web.UI.WebControls.Literal litDayWindow;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Label lblActiveCustomers;
        protected global::System.Web.UI.WebControls.Label lblLogins;
        protected global::System.Web.UI.WebControls.Label lblEventsWindow;
        protected global::System.Web.UI.WebControls.Label lblPageViews;
        protected global::System.Web.UI.WebControls.Label lblAddToCart;
        protected global::System.Web.UI.WebControls.Label lblCheckouts;
        protected global::System.Web.UI.WebControls.Repeater rptTopPages;
        protected global::System.Web.UI.WebControls.Panel pnlNoPages;
        protected global::System.Web.UI.WebControls.Repeater rptTopActions;
        protected global::System.Web.UI.WebControls.Panel pnlNoActions;
        protected global::System.Web.UI.WebControls.Repeater rptRecentCustomers;
        protected global::System.Web.UI.WebControls.Panel pnlNoCustomers;
        protected global::System.Web.UI.WebControls.Repeater rptRecentEvents;
    }
}
