//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneFit.BackendServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://schemas.datacontract.org/2004/07/PhoneFitService")]
    [System.SerializableAttribute()]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UserIsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UserAccountCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PhoneFit.BackendServiceReference.Cart[] CartsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string UserPasswordHash {
            get {
                return this.UserPasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordHashField, value) != true)) {
                    this.UserPasswordHashField = value;
                    this.RaisePropertyChanged("UserPasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string UserFirstName {
            get {
                return this.UserFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFirstNameField, value) != true)) {
                    this.UserFirstNameField = value;
                    this.RaisePropertyChanged("UserFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string UserSurname {
            get {
                return this.UserSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSurnameField, value) != true)) {
                    this.UserSurnameField = value;
                    this.RaisePropertyChanged("UserSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string UserPhoneNumber {
            get {
                return this.UserPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPhoneNumberField, value) != true)) {
                    this.UserPhoneNumberField = value;
                    this.RaisePropertyChanged("UserPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool UserIsActive {
            get {
                return this.UserIsActiveField;
            }
            set {
                if ((this.UserIsActiveField.Equals(value) != true)) {
                    this.UserIsActiveField = value;
                    this.RaisePropertyChanged("UserIsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime UserAccountCreated {
            get {
                return this.UserAccountCreatedField;
            }
            set {
                if ((this.UserAccountCreatedField.Equals(value) != true)) {
                    this.UserAccountCreatedField = value;
                    this.RaisePropertyChanged("UserAccountCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public PhoneFit.BackendServiceReference.Cart[] Carts {
            get {
                return this.CartsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartsField, value) != true)) {
                    this.CartsField = value;
                    this.RaisePropertyChanged("Carts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/PhoneFitService")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PhoneFit.BackendServiceReference.CartItem[] CartItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public PhoneFit.BackendServiceReference.CartItem[] CartItems {
            get {
                return this.CartItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartItemsField, value) != true)) {
                    this.CartItemsField = value;
                    this.RaisePropertyChanged("CartItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://schemas.datacontract.org/2004/07/PhoneFitService")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VariantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int VariantID {
            get {
                return this.VariantIDField;
            }
            set {
                if ((this.VariantIDField.Equals(value) != true)) {
                    this.VariantIDField = value;
                    this.RaisePropertyChanged("VariantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginInfo", Namespace="http://schemas.datacontract.org/2004/07/PhoneFitService")]
    [System.SerializableAttribute()]
    public partial class LoginInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginStatus {
            get {
                return this.LoginStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginStatusField, value) != true)) {
                    this.LoginStatusField = value;
                    this.RaisePropertyChanged("LoginStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneCatalogue", Namespace="http://schemas.datacontract.org/2004/07/PhoneFitService")]
    [System.SerializableAttribute()]
    public partial class PhoneCatalogue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StartingPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhoneModelID {
            get {
                return this.PhoneModelIDField;
            }
            set {
                if ((this.PhoneModelIDField.Equals(value) != true)) {
                    this.PhoneModelIDField = value;
                    this.RaisePropertyChanged("PhoneModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StartingPrice {
            get {
                return this.StartingPriceField;
            }
            set {
                if ((this.StartingPriceField.Equals(value) != true)) {
                    this.StartingPriceField = value;
                    this.RaisePropertyChanged("StartingPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneVariant", Namespace="http://schemas.datacontract.org/2004/07/PhoneFitService")]
    [System.SerializableAttribute()]
    public partial class PhoneVariant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VariantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RAMGBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StorageGBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LowStockLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PhoneFit.BackendServiceReference.CartItem[] CartItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VariantID {
            get {
                return this.VariantIDField;
            }
            set {
                if ((this.VariantIDField.Equals(value) != true)) {
                    this.VariantIDField = value;
                    this.RaisePropertyChanged("VariantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PhoneModelID {
            get {
                return this.PhoneModelIDField;
            }
            set {
                if ((this.PhoneModelIDField.Equals(value) != true)) {
                    this.PhoneModelIDField = value;
                    this.RaisePropertyChanged("PhoneModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int RAMGB {
            get {
                return this.RAMGBField;
            }
            set {
                if ((this.RAMGBField.Equals(value) != true)) {
                    this.RAMGBField = value;
                    this.RaisePropertyChanged("RAMGB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int StorageGB {
            get {
                return this.StorageGBField;
            }
            set {
                if ((this.StorageGBField.Equals(value) != true)) {
                    this.StorageGBField = value;
                    this.RaisePropertyChanged("StorageGB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Colour {
            get {
                return this.ColourField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourField, value) != true)) {
                    this.ColourField = value;
                    this.RaisePropertyChanged("Colour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int LowStockLevel {
            get {
                return this.LowStockLevelField;
            }
            set {
                if ((this.LowStockLevelField.Equals(value) != true)) {
                    this.LowStockLevelField = value;
                    this.RaisePropertyChanged("LowStockLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public PhoneFit.BackendServiceReference.CartItem[] CartItems {
            get {
                return this.CartItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartItemsField, value) != true)) {
                    this.CartItemsField = value;
                    this.RaisePropertyChanged("CartItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneSpecification", Namespace="http://schemas.datacontract.org/2004/07/PhoneFitService")]
    [System.SerializableAttribute()]
    public partial class PhoneSpecification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpecificationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ScreenSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScreenTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RefreshRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BatteryCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RearCameraMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FrontCameraMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Supports5GField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DualSIMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExpandableStorageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WaterResistanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpecificationID {
            get {
                return this.SpecificationIDField;
            }
            set {
                if ((this.SpecificationIDField.Equals(value) != true)) {
                    this.SpecificationIDField = value;
                    this.RaisePropertyChanged("SpecificationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PhoneModelID {
            get {
                return this.PhoneModelIDField;
            }
            set {
                if ((this.PhoneModelIDField.Equals(value) != true)) {
                    this.PhoneModelIDField = value;
                    this.RaisePropertyChanged("PhoneModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Processor {
            get {
                return this.ProcessorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessorField, value) != true)) {
                    this.ProcessorField = value;
                    this.RaisePropertyChanged("Processor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> ScreenSize {
            get {
                return this.ScreenSizeField;
            }
            set {
                if ((this.ScreenSizeField.Equals(value) != true)) {
                    this.ScreenSizeField = value;
                    this.RaisePropertyChanged("ScreenSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ScreenType {
            get {
                return this.ScreenTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreenTypeField, value) != true)) {
                    this.ScreenTypeField = value;
                    this.RaisePropertyChanged("ScreenType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> RefreshRate {
            get {
                return this.RefreshRateField;
            }
            set {
                if ((this.RefreshRateField.Equals(value) != true)) {
                    this.RefreshRateField = value;
                    this.RaisePropertyChanged("RefreshRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> BatteryCapacity {
            get {
                return this.BatteryCapacityField;
            }
            set {
                if ((this.BatteryCapacityField.Equals(value) != true)) {
                    this.BatteryCapacityField = value;
                    this.RaisePropertyChanged("BatteryCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<decimal> RearCameraMP {
            get {
                return this.RearCameraMPField;
            }
            set {
                if ((this.RearCameraMPField.Equals(value) != true)) {
                    this.RearCameraMPField = value;
                    this.RaisePropertyChanged("RearCameraMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<decimal> FrontCameraMP {
            get {
                return this.FrontCameraMPField;
            }
            set {
                if ((this.FrontCameraMPField.Equals(value) != true)) {
                    this.FrontCameraMPField = value;
                    this.RaisePropertyChanged("FrontCameraMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool Supports5G {
            get {
                return this.Supports5GField;
            }
            set {
                if ((this.Supports5GField.Equals(value) != true)) {
                    this.Supports5GField = value;
                    this.RaisePropertyChanged("Supports5G");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool DualSIM {
            get {
                return this.DualSIMField;
            }
            set {
                if ((this.DualSIMField.Equals(value) != true)) {
                    this.DualSIMField = value;
                    this.RaisePropertyChanged("DualSIM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool ExpandableStorage {
            get {
                return this.ExpandableStorageField;
            }
            set {
                if ((this.ExpandableStorageField.Equals(value) != true)) {
                    this.ExpandableStorageField = value;
                    this.RaisePropertyChanged("ExpandableStorage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string WaterResistance {
            get {
                return this.WaterResistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.WaterResistanceField, value) != true)) {
                    this.WaterResistanceField = value;
                    this.RaisePropertyChanged("WaterResistance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItemInfo", Namespace="http://schemas.datacontract.org/2004/07/PhoneFitService")]
    [System.SerializableAttribute()]
    public partial class CartItemInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LineTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariantDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VariantIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineTotal {
            get {
                return this.LineTotalField;
            }
            set {
                if ((this.LineTotalField.Equals(value) != true)) {
                    this.LineTotalField = value;
                    this.RaisePropertyChanged("LineTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhoneModelID {
            get {
                return this.PhoneModelIDField;
            }
            set {
                if ((this.PhoneModelIDField.Equals(value) != true)) {
                    this.PhoneModelIDField = value;
                    this.RaisePropertyChanged("PhoneModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VariantDescription {
            get {
                return this.VariantDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.VariantDescriptionField, value) != true)) {
                    this.VariantDescriptionField = value;
                    this.RaisePropertyChanged("VariantDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VariantID {
            get {
                return this.VariantIDField;
            }
            set {
                if ((this.VariantIDField.Equals(value) != true)) {
                    this.VariantIDField = value;
                    this.RaisePropertyChanged("VariantID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/PhoneFitService")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UserAccountCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UserIsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserAccountCreated {
            get {
                return this.UserAccountCreatedField;
            }
            set {
                if ((this.UserAccountCreatedField.Equals(value) != true)) {
                    this.UserAccountCreatedField = value;
                    this.RaisePropertyChanged("UserAccountCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UserIsActive {
            get {
                return this.UserIsActiveField;
            }
            set {
                if ((this.UserIsActiveField.Equals(value) != true)) {
                    this.UserIsActiveField = value;
                    this.RaisePropertyChanged("UserIsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPhoneNumber {
            get {
                return this.UserPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPhoneNumberField, value) != true)) {
                    this.UserPhoneNumberField = value;
                    this.RaisePropertyChanged("UserPhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackendServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        int RegisterUser(PhoneFit.BackendServiceReference.UserAccount userAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.Threading.Tasks.Task<int> RegisterUserAsync(PhoneFit.BackendServiceReference.UserAccount userAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        PhoneFit.BackendServiceReference.LoginInfo LoginUser(string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.LoginInfo> LoginUserAsync(string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActivePhones", ReplyAction="http://tempuri.org/IService1/GetActivePhonesResponse")]
        PhoneFit.BackendServiceReference.PhoneCatalogue[] GetActivePhones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActivePhones", ReplyAction="http://tempuri.org/IService1/GetActivePhonesResponse")]
        System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.PhoneCatalogue[]> GetActivePhonesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPhoneByID", ReplyAction="http://tempuri.org/IService1/GetPhoneByIDResponse")]
        PhoneFit.BackendServiceReference.PhoneCatalogue GetPhoneByID(int phoneModelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPhoneByID", ReplyAction="http://tempuri.org/IService1/GetPhoneByIDResponse")]
        System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.PhoneCatalogue> GetPhoneByIDAsync(int phoneModelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVariantsByPhoneID", ReplyAction="http://tempuri.org/IService1/GetVariantsByPhoneIDResponse")]
        PhoneFit.BackendServiceReference.PhoneVariant[] GetVariantsByPhoneID(int phoneModelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVariantsByPhoneID", ReplyAction="http://tempuri.org/IService1/GetVariantsByPhoneIDResponse")]
        System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.PhoneVariant[]> GetVariantsByPhoneIDAsync(int phoneModelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpecificationByPhoneID", ReplyAction="http://tempuri.org/IService1/GetSpecificationByPhoneIDResponse")]
        PhoneFit.BackendServiceReference.PhoneSpecification GetSpecificationByPhoneID(int phoneModelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpecificationByPhoneID", ReplyAction="http://tempuri.org/IService1/GetSpecificationByPhoneIDResponse")]
        System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.PhoneSpecification> GetSpecificationByPhoneIDAsync(int phoneModelID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        bool AddToCart(int userID, int variantID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        System.Threading.Tasks.Task<bool> AddToCartAsync(int userID, int variantID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartItems", ReplyAction="http://tempuri.org/IService1/GetCartItemsResponse")]
        PhoneFit.BackendServiceReference.CartItemInfo[] GetCartItems(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartItems", ReplyAction="http://tempuri.org/IService1/GetCartItemsResponse")]
        System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.CartItemInfo[]> GetCartItemsAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangeCartItemQuantity", ReplyAction="http://tempuri.org/IService1/ChangeCartItemQuantityResponse")]
        bool ChangeCartItemQuantity(int userID, int cartItemID, int quantityChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangeCartItemQuantity", ReplyAction="http://tempuri.org/IService1/ChangeCartItemQuantityResponse")]
        System.Threading.Tasks.Task<bool> ChangeCartItemQuantityAsync(int userID, int cartItemID, int quantityChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveCartItem", ReplyAction="http://tempuri.org/IService1/RemoveCartItemResponse")]
        bool RemoveCartItem(int userID, int cartItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveCartItem", ReplyAction="http://tempuri.org/IService1/RemoveCartItemResponse")]
        System.Threading.Tasks.Task<bool> RemoveCartItemAsync(int userID, int cartItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClearCart", ReplyAction="http://tempuri.org/IService1/ClearCartResponse")]
        bool ClearCart(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ClearCart", ReplyAction="http://tempuri.org/IService1/ClearCartResponse")]
        System.Threading.Tasks.Task<bool> ClearCartAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        PhoneFit.BackendServiceReference.UserInfo[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsers", ReplyAction="http://tempuri.org/IService1/GetUsersResponse")]
        System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.UserInfo[]> GetUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PhoneFit.BackendServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PhoneFit.BackendServiceReference.IService1>, PhoneFit.BackendServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegisterUser(PhoneFit.BackendServiceReference.UserAccount userAccount) {
            return base.Channel.RegisterUser(userAccount);
        }
        
        public System.Threading.Tasks.Task<int> RegisterUserAsync(PhoneFit.BackendServiceReference.UserAccount userAccount) {
            return base.Channel.RegisterUserAsync(userAccount);
        }
        
        public PhoneFit.BackendServiceReference.LoginInfo LoginUser(string email, string passwordHash) {
            return base.Channel.LoginUser(email, passwordHash);
        }
        
        public System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.LoginInfo> LoginUserAsync(string email, string passwordHash) {
            return base.Channel.LoginUserAsync(email, passwordHash);
        }
        
        public PhoneFit.BackendServiceReference.PhoneCatalogue[] GetActivePhones() {
            return base.Channel.GetActivePhones();
        }
        
        public System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.PhoneCatalogue[]> GetActivePhonesAsync() {
            return base.Channel.GetActivePhonesAsync();
        }
        
        public PhoneFit.BackendServiceReference.PhoneCatalogue GetPhoneByID(int phoneModelID) {
            return base.Channel.GetPhoneByID(phoneModelID);
        }
        
        public System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.PhoneCatalogue> GetPhoneByIDAsync(int phoneModelID) {
            return base.Channel.GetPhoneByIDAsync(phoneModelID);
        }
        
        public PhoneFit.BackendServiceReference.PhoneVariant[] GetVariantsByPhoneID(int phoneModelID) {
            return base.Channel.GetVariantsByPhoneID(phoneModelID);
        }
        
        public System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.PhoneVariant[]> GetVariantsByPhoneIDAsync(int phoneModelID) {
            return base.Channel.GetVariantsByPhoneIDAsync(phoneModelID);
        }
        
        public PhoneFit.BackendServiceReference.PhoneSpecification GetSpecificationByPhoneID(int phoneModelID) {
            return base.Channel.GetSpecificationByPhoneID(phoneModelID);
        }
        
        public System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.PhoneSpecification> GetSpecificationByPhoneIDAsync(int phoneModelID) {
            return base.Channel.GetSpecificationByPhoneIDAsync(phoneModelID);
        }
        
        public bool AddToCart(int userID, int variantID, int quantity) {
            return base.Channel.AddToCart(userID, variantID, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> AddToCartAsync(int userID, int variantID, int quantity) {
            return base.Channel.AddToCartAsync(userID, variantID, quantity);
        }
        
        public PhoneFit.BackendServiceReference.CartItemInfo[] GetCartItems(int userID) {
            return base.Channel.GetCartItems(userID);
        }
        
        public System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.CartItemInfo[]> GetCartItemsAsync(int userID) {
            return base.Channel.GetCartItemsAsync(userID);
        }
        
        public bool ChangeCartItemQuantity(int userID, int cartItemID, int quantityChange) {
            return base.Channel.ChangeCartItemQuantity(userID, cartItemID, quantityChange);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeCartItemQuantityAsync(int userID, int cartItemID, int quantityChange) {
            return base.Channel.ChangeCartItemQuantityAsync(userID, cartItemID, quantityChange);
        }
        
        public bool RemoveCartItem(int userID, int cartItemID) {
            return base.Channel.RemoveCartItem(userID, cartItemID);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveCartItemAsync(int userID, int cartItemID) {
            return base.Channel.RemoveCartItemAsync(userID, cartItemID);
        }
        
        public bool ClearCart(int userID) {
            return base.Channel.ClearCart(userID);
        }
        
        public System.Threading.Tasks.Task<bool> ClearCartAsync(int userID) {
            return base.Channel.ClearCartAsync(userID);
        }
        
        public PhoneFit.BackendServiceReference.UserInfo[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<PhoneFit.BackendServiceReference.UserInfo[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
    }
}
